services:
  chessserverprogram:
    image: ${DOCKER_REGISTRY-}chessserverprogram
    ports:
    - 1557:1557
    build:
      context: .
      dockerfile: ChessServerProgram/Dockerfile
  mysql:
    image: mysql
    restart: always
    ports: 
    - 3306:3306
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: 1q2w3e4r!
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  #mongodb:
  #  image: mongo
  #  restart: always
  #  ports:
  #  - 27017:27017
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: 1q2w3e4r!
  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - 6379:6379
      